
###
GET http://localhost:2394/api/competition/id/2
content-type: application/json
identifyId: asdqdszd
userId: 8

###
GET http://localhost:2394/api/competition/detail/8
content-type: application/json
identifyId: S7HlWCbUDEU84limyu51NN1wiSo1
userId: 9



###
GET http://localhost:2394/api/competition/monthly/2022/3
content-type: application/json
identifyId: asdqdszd
userId: 8


###
POST http://localhost:2394/api/competition
content-type: application/json
identifyId: 1yPpFJECu3Zso1SR9mTBYLhZWog2
userId: 1

{
    "title": "도전해라2222 2222222222",
    "message": "아무나 오지마라 혼난다",
    "matchTime": "{{$localDatetime 'YYYY-MM-DD HH:mm:ss'}}",
    "location": "서울 강남구 학동로 235 로이빌딩",
    "locationName": "ALOHA BOXING GYM"
}

###
POST http://localhost:2394/api/competition/challenge
content-type: application/json
identifyId: S7HlWCbUDEU84limyu51NN1wiSo1
userId: 9

{
    "competitionId": 8
}

###
POST http://localhost:2394/api/competition/select/challenger
content-type: application/json
identifyId: S7HlWCbUDEU84limyu51NN1wiSo1
userId: 9

{
    "competitionId": 8,
    "challengerId": 12
}
