
###
GET http://localhost:2394/api/user/me
content-type: application/json
identifyId: asdqdszd
userId: 8


###
GET http://localhost:2394/api/user/all/me
content-type: application/json
identifyId: asdqdszd
userId: 8


###
GET http://localhost:2394/api/user/id/2
content-type: application/json
identifyId: asdqdszd
userId: 1

###
GET http://localhost:2394/api/user/all/me
content-type: application/json
identifyId: asdqdszd
userId: 1

###
GET http://localhost:2394/api/user/me
content-type: application/json
identifyId: asdqdszd
userId: 4


###
POST http://localhost:2394/api/user/update
content-type: application/json
identifyId: TvUhKduk2neLamvlMRqlrOTZwue2
userId: 5

{
    "nickName": "hahaha"
}

###
PATCH http://localhost:2394/api/user/me
content-type: application/json
identifyId: asdqdszd
userId: 3

{
    "nickName": "HIHIHI"
}