
###
POST http://localhost:2394/api/account/
content-type: application/json
x-access-token: admin

{
    "identifyId": "aaaa4444444"
}


###
POST http://localhost:2394/api/sign/
content-type: application/json

{
    "identifyId": "1yPpFJECu3Zso1SR9mTBYLhZWog2",
    "email":"kakak@kaka.com","joinType":"0"
}

